language: php

php:
    - 7.3
    - 7.4
    - 8.0

sudo: false

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit tests/

after_success:
    - bash <(curl -s https://codecov.io/bash)